# Generated by Django 4.1.7 on 2023-04-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=250, unique=True)),
                (
                    "ncm_naladish",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("o_cst", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("cfop", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "measurement_unit",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "profit_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "icms_base_calc",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("icms_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("icms_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("ipi_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ipi_rate", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
