# Generated by Django 4.1.7 on 2023-04-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsiblecompany",
            name="logo",
            field=models.ImageField(blank=True, upload_to="company_logos/%Y/%m/%d/"),
        ),
    ]
