# Generated by Django 4.1.7 on 2023-04-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0002_responsiblecompany_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsiblecompany",
            name="address_number",
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
