# Generated by Django 4.1.7 on 2023-04-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0003_alter_product_icms_base_calc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(default="teste", max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="profit_percentage",
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
