# Generated by Django 4.1.7 on 2023-04-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0004_product_name_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="profit_percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
