# Generated by Django 4.1.7 on 2023-04-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0004_alter_responsiblecompany_municipal_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsiblecompany",
            name="state_registration",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
