# Generated by Django 4.1.7 on 2023-04-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0005_alter_responsiblecompany_state_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsiblecompany",
            name="municipal_registration",
            field=models.PositiveSmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="responsiblecompany",
            name="state_registration",
            field=models.PositiveSmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
