# Generated by Django 4.1.7 on 2023-04-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0005_alter_product_profit_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="profit_percentage",
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
