# Generated by Django 4.1.7 on 2023-04-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "registrations",
            "0006_alter_responsiblecompany_municipal_registration_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsiblecompany",
            name="municipal_registration",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="responsiblecompany",
            name="state_registration",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
