# Generated by Django 4.1.7 on 2023-04-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "registrations",
            "0007_alter_responsiblecompany_municipal_registration_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsiblecompany",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="company_logos/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="responsiblecompany",
            name="phone",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
