# Generated by Django 4.1.7 on 2023-04-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0007_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_name", models.CharField(max_length=250)),
                ("address_number", models.SmallIntegerField()),
                (
                    "address_complement",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("neighborhood", models.CharField(max_length=250)),
                ("city", models.CharField(max_length=250)),
                ("state", models.CharField(max_length=2)),
                ("postal_code", models.SmallIntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.SmallIntegerField(blank=True, null=True)),
                ("mobile_phone", models.SmallIntegerField()),
                (
                    "person_type",
                    models.CharField(
                        choices=[("PF", "Pessoa Física"), ("PJ", "Pessoa Jurídica")],
                        default="PJ",
                        max_length=2,
                    ),
                ),
                (
                    "identification_number",
                    models.PositiveSmallIntegerField(unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("brand_name", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "municipal_registration",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "state_registration",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
