# Generated by Django 4.1.7 on 2023-04-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0008_alter_responsiblecompany_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsiblecompany",
            name="address_complement",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
