# Generated by Django 4.1.7 on 2023-04-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="identification_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
